### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by lzm-01** [codgodtao/CrossDiff#1]
Sorry to bother you, I wanted to ask if the dataset used in your work is the same as PanCollection.

**Comment by codgodtao** [comment]
no, the dataset used in this paper is not same with Pancollection, PanCollection only has WV3, GF2 and QB datasets, We collected WV4, QB and WV2 Dataset for training and testing in our paper.  But the model could be trained based on PanCollection, the only difference is spectral number and spatial resolution settings

**Comment by lzm-01** [comment]
thanks!
